services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on: #先にdbから起動させる
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data # データを永続化するための設定
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
     - "5432:5432"
    restart: always
volumes:
  postgres_data:
  bundle_data:
  node_modules:
